/**
 * Component Registry - Single source of truth for all component metadata
 * Used by grid view, simulator, props editor, and code generator
 */

import type { ComponentMeta, ComponentCategory } from './types'

export const COMPONENT_REGISTRY: ComponentMeta[] = [
  // ============ UI Components (38) ============
  {
    name: 'Accordion',
    slug: 'accordion',
    description: 'Expandable content sections',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Avatar',
    slug: 'avatar',
    description: 'User profile image with fallback',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { Avatar, AvatarImage, AvatarFallback } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Badge',
    slug: 'badge',
    description: 'Display status or labels',
    category: 'ui',
    variantCount: 4,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'secondary', 'destructive', 'outline'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { Badge } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Banner',
    slug: 'banner',
    description: 'Full-width notification banner',
    category: 'ui',
    variantCount: 6,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'info', 'warning', 'error', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { Banner } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Bottom Sheet',
    slug: 'bottom-sheet',
    description: 'Slide-up panel from bottom of screen',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { BottomSheet, BottomSheetTrigger, BottomSheetContent, BottomSheetHeader, BottomSheetTitle, BottomSheetDescription } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Button',
    slug: 'button',
    description: 'Trigger actions with various styles and sizes',
    category: 'ui',
    variantCount: 6,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'], default: 'default', description: 'Visual style variant' },
      { name: 'size', type: 'select', options: ['default', 'sm', 'lg', 'icon'], default: 'default', description: 'Button size' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the button' },
    ],
    defaultProps: { variant: 'default', size: 'default', disabled: false },
    importStatement: "import { Button } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Card',
    slug: 'card',
    description: 'Container for grouped content',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Carousel',
    slug: 'carousel',
    description: 'Swipeable content carousel',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'showDots', type: 'boolean', default: true, description: 'Show navigation dots' },
      { name: 'showArrows', type: 'boolean', default: true, description: 'Show arrow navigation' },
    ],
    defaultProps: { variant: 'default', showDots: true, showArrows: true },
    importStatement: "import { Carousel, CarouselItem } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Checkbox',
    slug: 'checkbox',
    description: 'Selectable checkbox with glass variants',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'checked', type: 'boolean', default: false, description: 'Checked state' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the checkbox' },
    ],
    defaultProps: { variant: 'default', checked: false, disabled: false },
    importStatement: "import { Checkbox } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Chip',
    slug: 'chip',
    description: 'Compact element for filters and selections',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'type', type: 'select', options: ['filter', 'input', 'suggestion'], default: 'filter', description: 'Chip behavior type' },
      { name: 'selected', type: 'boolean', default: false, description: 'Selected state' },
    ],
    defaultProps: { variant: 'default', type: 'filter', selected: false },
    importStatement: "import { Chip } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Context Menu',
    slug: 'context-menu',
    description: 'Right-click context menu',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { ContextMenu, ContextMenuTrigger, ContextMenuContent, ContextMenuItem } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Data Table',
    slug: 'data-table',
    description: 'Sortable data table with columns',
    category: 'ui',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid'], default: 'default', description: 'Visual style variant' },
      { name: 'sortable', type: 'boolean', default: true, description: 'Enable column sorting' },
      { name: 'striped', type: 'boolean', default: false, description: 'Striped row styling' },
    ],
    defaultProps: { variant: 'default', sortable: true, striped: false },
    importStatement: "import { DataTable } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Date Picker',
    slug: 'date-picker',
    description: 'Calendar date selection component',
    category: 'ui',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the picker' },
    ],
    defaultProps: { variant: 'default', disabled: false },
    importStatement: "import { DatePicker } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Dialog',
    slug: 'dialog',
    description: 'Modal dialog for focused interactions',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Divider',
    slug: 'divider',
    description: 'Glass-morphism visual divider',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'orientation', type: 'select', options: ['horizontal', 'vertical'], default: 'horizontal', description: 'Divider orientation' },
    ],
    defaultProps: { variant: 'default', orientation: 'horizontal' },
    importStatement: "import { Divider } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Dropdown Menu',
    slug: 'dropdown-menu',
    description: 'Contextual menu with actions',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Empty State',
    slug: 'empty-state',
    description: 'Placeholder for empty content areas',
    category: 'ui',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { EmptyState } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'FAB',
    slug: 'fab',
    description: 'Floating action button for primary actions',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'size', type: 'select', options: ['sm', 'default', 'lg'], default: 'default', description: 'Button size' },
    ],
    defaultProps: { variant: 'default', size: 'default' },
    importStatement: "import { FAB } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Icon Button',
    slug: 'icon-button',
    description: 'Circular button for icon actions',
    category: 'ui',
    variantCount: 4,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'ghost', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'size', type: 'select', options: ['sm', 'default', 'lg'], default: 'default', description: 'Button size' },
    ],
    defaultProps: { variant: 'default', size: 'default' },
    importStatement: "import { IconButton } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Input',
    slug: 'input',
    description: 'Text input field for forms',
    category: 'ui',
    variantCount: 1,
    props: [
      { name: 'type', type: 'select', options: ['text', 'email', 'password', 'number', 'search'], default: 'text', description: 'Input type' },
      { name: 'placeholder', type: 'text', default: 'Enter text...', description: 'Placeholder text' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the input' },
    ],
    defaultProps: { type: 'text', placeholder: 'Enter text...', disabled: false },
    importStatement: "import { Input } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'List',
    slug: 'list',
    description: 'Organized content in vertical lists',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'dense', type: 'boolean', default: false, description: 'Compact item spacing' },
    ],
    defaultProps: { variant: 'default', dense: false },
    importStatement: "import { List, ListItem, ListItemText, ListItemTitle, ListItemDescription } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Progress',
    slug: 'progress',
    description: 'Linear and circular progress indicators',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'type', type: 'select', options: ['linear', 'circular'], default: 'linear', description: 'Progress type' },
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'value', type: 'number', default: 60, description: 'Progress value (0-100)' },
    ],
    defaultProps: { type: 'linear', variant: 'default', value: 60 },
    importStatement: "import { Progress } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Radio Group',
    slug: 'radio-group',
    description: 'Radio button group for single selection',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { RadioGroup, RadioGroupItem } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Segmented Button',
    slug: 'segmented-button',
    description: 'Segmented toggle button group',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { SegmentedButton } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Select',
    slug: 'select',
    description: 'Dropdown selection component',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Separator',
    slug: 'separator',
    description: 'Visual divider between content',
    category: 'ui',
    variantCount: 1,
    props: [
      { name: 'orientation', type: 'select', options: ['horizontal', 'vertical'], default: 'horizontal', description: 'Separator orientation' },
    ],
    defaultProps: { orientation: 'horizontal' },
    importStatement: "import { Separator } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Side Sheet',
    slug: 'side-sheet',
    description: 'Slide-in panel from side of screen',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { SideSheet, SideSheetTrigger, SideSheetContent, SideSheetHeader, SideSheetTitle, SideSheetDescription } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Skeleton',
    slug: 'skeleton',
    description: 'Loading placeholder animation',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['rectangle', 'circle', 'text'], default: 'rectangle', description: 'Skeleton shape' },
    ],
    defaultProps: { variant: 'rectangle' },
    importStatement: "import { Skeleton } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Slider',
    slug: 'slider',
    description: 'Range slider for value selection',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the slider' },
    ],
    defaultProps: { variant: 'default', disabled: false },
    importStatement: "import { Slider } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Snackbar',
    slug: 'snackbar',
    description: 'Temporary notification message',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { Snackbar } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Speed Dial',
    slug: 'speed-dial',
    description: 'Expandable floating action menu',
    category: 'ui',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'direction', type: 'select', options: ['up', 'down', 'left', 'right'], default: 'up', description: 'Expansion direction' },
    ],
    defaultProps: { variant: 'default', direction: 'up' },
    importStatement: "import { SpeedDial } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Stepper',
    slug: 'stepper',
    description: 'Step-by-step progress indicator',
    category: 'ui',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid'], default: 'default', description: 'Visual style variant' },
      { name: 'orientation', type: 'select', options: ['horizontal', 'vertical'], default: 'horizontal', description: 'Stepper orientation' },
      { name: 'activeStep', type: 'number', default: 1, description: 'Current active step (0-indexed)' },
    ],
    defaultProps: { variant: 'default', orientation: 'horizontal', activeStep: 1 },
    importStatement: "import { Stepper } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Switch',
    slug: 'switch',
    description: 'On/off toggle switch',
    category: 'ui',
    variantCount: 1,
    props: [
      { name: 'checked', type: 'boolean', default: false, description: 'Checked state' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the switch' },
    ],
    defaultProps: { checked: false, disabled: false },
    importStatement: "import { Switch } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Textarea',
    slug: 'textarea',
    description: 'Multi-line text input',
    category: 'ui',
    variantCount: 1,
    props: [
      { name: 'placeholder', type: 'text', default: 'Enter message...', description: 'Placeholder text' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the textarea' },
    ],
    defaultProps: { placeholder: 'Enter message...', disabled: false },
    importStatement: "import { Textarea } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Time Picker',
    slug: 'time-picker',
    description: 'Time selection component',
    category: 'ui',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'format', type: 'select', options: ['12h', '24h'], default: '12h', description: 'Time format' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable the picker' },
    ],
    defaultProps: { variant: 'default', format: '12h', disabled: false },
    importStatement: "import { TimePicker } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Timeline',
    slug: 'timeline',
    description: 'Vertical timeline for sequential events',
    category: 'ui',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { Timeline } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Toggle',
    slug: 'toggle',
    description: 'Two-state toggle button',
    category: 'ui',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'outline'], default: 'default', description: 'Visual style variant' },
      { name: 'size', type: 'select', options: ['default', 'sm', 'lg'], default: 'default', description: 'Toggle size' },
      { name: 'pressed', type: 'boolean', default: false, description: 'Pressed state' },
    ],
    defaultProps: { variant: 'default', size: 'default', pressed: false },
    importStatement: "import { Toggle } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Tooltip',
    slug: 'tooltip',
    description: 'Show hints on hover',
    category: 'ui',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },

  // ============ Chat Components (4) ============
  {
    name: 'Chat Bubble',
    slug: 'chat-bubble',
    description: 'Message bubble for chat interfaces',
    category: 'chat',
    variantCount: 2,
    props: [
      { name: 'role', type: 'select', options: ['user', 'assistant'], default: 'assistant', description: 'Message sender role' },
      { name: 'timestamp', type: 'text', default: '', description: 'Optional timestamp' },
    ],
    defaultProps: { role: 'assistant', timestamp: '' },
    importStatement: "import { ChatBubble } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Chat Input',
    slug: 'chat-input',
    description: 'Input field for chat messages',
    category: 'chat',
    variantCount: 1,
    props: [
      { name: 'placeholder', type: 'text', default: 'Type a message...', description: 'Placeholder text' },
      { name: 'disabled', type: 'boolean', default: false, description: 'Disable input' },
    ],
    defaultProps: { placeholder: 'Type a message...', disabled: false },
    importStatement: "import { ChatInput } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Message List',
    slug: 'message-list',
    description: 'Scrollable container for messages',
    category: 'chat',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { MessageList } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Typing Indicator',
    slug: 'typing-indicator',
    description: 'Animated typing dots',
    category: 'chat',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { TypingIndicator } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },

  // ============ Layout Components (3) ============
  {
    name: 'Container',
    slug: 'container',
    description: 'Centered content wrapper',
    category: 'layout',
    variantCount: 1,
    props: [
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg', 'xl', 'full'], default: 'lg', description: 'Max width size' },
    ],
    defaultProps: { size: 'lg' },
    importStatement: "import { Container } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Header',
    slug: 'header',
    description: 'App header with navigation',
    category: 'layout',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { Header } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Sidebar',
    slug: 'sidebar',
    description: 'Navigation sidebar panel',
    category: 'layout',
    variantCount: 1,
    props: [
      { name: 'collapsed', type: 'boolean', default: false, description: 'Collapsed state' },
    ],
    defaultProps: { collapsed: false },
    importStatement: "import { Sidebar } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },

  // ============ Theme Components (2) ============
  {
    name: 'Theme Provider',
    slug: 'theme-provider',
    description: 'Theme context provider',
    category: 'theme',
    variantCount: 1,
    props: [
      { name: 'defaultTheme', type: 'select', options: ['light', 'dark', 'system'], default: 'system', description: 'Default theme' },
    ],
    defaultProps: { defaultTheme: 'system' },
    importStatement: "import { ThemeProvider } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Theme Toggle',
    slug: 'theme-toggle',
    description: 'Light/dark mode toggle',
    category: 'theme',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { ThemeToggle } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },

  // ============ Navigation Components (7) ============
  {
    name: 'Bottom Navigation',
    slug: 'bottom-navigation',
    description: 'Bottom navigation bar for mobile',
    category: 'navigation',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { BottomNavigation } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Breadcrumbs',
    slug: 'breadcrumbs',
    description: 'Navigation breadcrumb trail',
    category: 'navigation',
    variantCount: 1,
    props: [],
    defaultProps: {},
    importStatement: "import { Breadcrumbs } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Navigation Drawer',
    slug: 'navigation-drawer',
    description: 'Slide-out navigation drawer',
    category: 'navigation',
    variantCount: 1,
    props: [
      { name: 'mode', type: 'select', options: ['permanent', 'modal', 'bottom'], default: 'modal', description: 'Drawer mode' },
    ],
    defaultProps: { mode: 'modal' },
    importStatement: "import { NavigationDrawer, NavigationDrawerTrigger } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: true,
  },
  {
    name: 'Navigation Rail',
    slug: 'navigation-rail',
    description: 'Vertical side navigation rail',
    category: 'navigation',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'collapsed', type: 'boolean', default: true, description: 'Collapsed mode' },
    ],
    defaultProps: { variant: 'default', collapsed: true },
    importStatement: "import { NavigationRail } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Search Bar',
    slug: 'search-bar',
    description: 'Expandable search input with suggestions',
    category: 'navigation',
    variantCount: 2,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { SearchBar } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Tabs',
    slug: 'tabs',
    description: 'Tab navigation for content sections',
    category: 'navigation',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
    ],
    defaultProps: { variant: 'default' },
    importStatement: "import { Tabs } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },
  {
    name: 'Top App Bar',
    slug: 'top-app-bar',
    description: 'Top navigation bar with title and actions',
    category: 'navigation',
    variantCount: 3,
    props: [
      { name: 'variant', type: 'select', options: ['default', 'solid', 'spatial'], default: 'default', description: 'Visual style variant' },
      { name: 'title', type: 'text', default: 'App Title', description: 'Bar title text' },
    ],
    defaultProps: { variant: 'default', title: 'App Title' },
    importStatement: "import { TopAppBar } from 'glasscn-ui'",
    hasChildren: false,
    isCompound: false,
  },

  // ============ Motion Components (3) ============
  {
    name: 'Fade In',
    slug: 'fade-in',
    description: 'Fade-in animation wrapper',
    category: 'motion',
    variantCount: 1,
    props: [
      { name: 'duration', type: 'number', default: 0.3, description: 'Animation duration in seconds' },
      { name: 'delay', type: 'number', default: 0, description: 'Animation delay in seconds' },
    ],
    defaultProps: { duration: 0.3, delay: 0 },
    importStatement: "import { FadeIn } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Scale In',
    slug: 'scale-in',
    description: 'Scale-in animation wrapper',
    category: 'motion',
    variantCount: 1,
    props: [
      { name: 'duration', type: 'number', default: 0.2, description: 'Animation duration in seconds' },
      { name: 'delay', type: 'number', default: 0, description: 'Animation delay in seconds' },
      { name: 'initialScale', type: 'number', default: 0.95, description: 'Initial scale value' },
    ],
    defaultProps: { duration: 0.2, delay: 0, initialScale: 0.95 },
    importStatement: "import { ScaleIn } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
  {
    name: 'Slide Up',
    slug: 'slide-up',
    description: 'Slide-up animation wrapper',
    category: 'motion',
    variantCount: 1,
    props: [
      { name: 'duration', type: 'number', default: 0.3, description: 'Animation duration in seconds' },
      { name: 'delay', type: 'number', default: 0, description: 'Animation delay in seconds' },
      { name: 'offset', type: 'number', default: 10, description: 'Slide offset in pixels' },
    ],
    defaultProps: { duration: 0.3, delay: 0, offset: 10 },
    importStatement: "import { SlideUp } from 'glasscn-ui'",
    hasChildren: true,
    isCompound: false,
  },
]

// ============ Helper Functions ============

export function getComponent(slug: string): ComponentMeta | undefined {
  return COMPONENT_REGISTRY.find((c) => c.slug === slug)
}

export function getComponentsByCategory(category: ComponentCategory): ComponentMeta[] {
  return COMPONENT_REGISTRY.filter((c) => c.category === category)
}

export function getAllCategories(): ComponentCategory[] {
  return ['ui', 'chat', 'layout', 'theme', 'navigation', 'motion']
}

export function getCategoryLabel(category: ComponentCategory): string {
  const labels: Record<ComponentCategory, string> = {
    ui: 'UI Components',
    chat: 'Chat Components',
    layout: 'Layout Components',
    theme: 'Theme',
    navigation: 'Navigation Components',
    motion: 'Motion Components',
  }
  return labels[category]
}
